
import { Prospect, Team, Position, DraftPick } from './types';

export const ALL_TEAMS: Record<string, Team> = {
  LV: { id: 'LV', name: 'Las Vegas Raiders', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png', color: '#000000', needs: ['QB', 'OT', 'CB', 'EDGE', 'DL'] },
  NYJ: { id: 'NYJ', name: 'New York Jets', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png', color: '#125740', needs: ['WR', 'OT', 'S', 'LB', 'DL'] },
  ARI: { id: 'ARI', name: 'Arizona Cardinals', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png', color: '#97233f', needs: ['CB', 'DL', 'OT', 'EDGE', 'LB'] },
  TEN: { id: 'TEN', name: 'Tennessee Titans', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png', color: '#4b92db', needs: ['WR', 'OT', 'EDGE', 'LB', 'CB'] },
  NYG: { id: 'NYG', name: 'New York Giants', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png', color: '#0b2265', needs: ['QB', 'WR', 'RB', 'OT', 'CB'] },
  CLE: { id: 'CLE', name: 'Cleveland Browns', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png', color: '#311d00', needs: ['OT', 'WR', 'LB', 'DL', 'S'] },
  WAS: { id: 'WAS', name: 'Washington Commanders', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/was.png', color: '#5a1414', needs: ['OT', 'EDGE', 'CB', 'LB', 'S'] },
  NO: { id: 'NO', name: 'New Orleans Saints', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png', color: '#d3bc8d', needs: ['QB', 'OT', 'EDGE', 'WR', 'DL'] },
  KC: { id: 'KC', name: 'Kansas City Chiefs', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png', color: '#e31837', needs: ['WR', 'OT', 'CB', 'EDGE', 'DL'] },
  CIN: { id: 'CIN', name: 'Cincinnati Bengals', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png', color: '#fb4f14', needs: ['OT', 'DL', 'WR', 'CB', 'TE'] },
  MIA: { id: 'MIA', name: 'Miami Dolphins', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png', color: '#008e97', needs: ['IOL', 'OT', 'WR', 'DL', 'LB'] },
  DAL: { id: 'DAL', name: 'Dallas Cowboys', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png', color: '#003594', needs: ['RB', 'WR', 'EDGE', 'DL', 'LB'] },
  LAR: { id: 'LAR', name: 'LA Rams', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png', color: '#003594', needs: ['OT', 'CB', 'WR', 'LB', 'DL'] },
  BAL: { id: 'BAL', name: 'Baltimore Ravens', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png', color: '#241773', needs: ['OT', 'WR', 'CB', 'EDGE', 'IOL'] },
  TB: { id: 'TB', name: 'Tampa Bay Buccaneers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png', color: '#d50a0a', needs: ['CB', 'EDGE', 'DL', 'WR', 'OT'] },
  DET: { id: 'DET', name: 'Detroit Lions', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png', color: '#0076b6', needs: ['EDGE', 'CB', 'DL', 'WR', 'S'] },
  MIN: { id: 'MIN', name: 'Minnesota Vikings', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png', color: '#4f2683', needs: ['DL', 'CB', 'WR', 'OT', 'IOL'] },
  CAR: { id: 'CAR', name: 'Carolina Panthers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png', color: '#0085ca', needs: ['WR', 'EDGE', 'LB', 'CB', 'S'] },
  PIT: { id: 'PIT', name: 'Pittsburgh Steelers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png', color: '#ffb612', needs: ['WR', 'OT', 'CB', 'EDGE', 'DL'] },
  LAC: { id: 'LAC', name: 'LA Chargers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png', color: '#0080c6', needs: ['WR', 'CB', 'DL', 'LB', 'TE'] },
  PHI: { id: 'PHI', name: 'Philadelphia Eagles', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png', color: '#004c54', needs: ['CB', 'WR', 'EDGE', 'DL', 'S'] },
  BUF: { id: 'BUF', name: 'Buffalo Bills', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png', color: '#00338d', needs: ['WR', 'EDGE', 'DL', 'CB', 'S'] },
  CHI: { id: 'CHI', name: 'Chicago Bears', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png', color: '#c83803', needs: ['EDGE', 'OT', 'WR', 'DL', 'CB'] },
  SF: { id: 'SF', name: 'San Francisco 49ers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png', color: '#aa0000', needs: ['OT', 'CB', 'EDGE', 'DL', 'WR'] },
  HOU: { id: 'HOU', name: 'Houston Texans', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png', color: '#03202f', needs: ['DL', 'EDGE', 'CB', 'LB', 'S'] },
  NE: { id: 'NE', name: 'New England Patriots', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png', color: '#002244', needs: ['OT', 'WR', 'CB', 'EDGE', 'LB'] },
  DEN: { id: 'DEN', name: 'Denver Broncos', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png', color: '#fb4f14', needs: ['QB', 'WR', 'OT', 'EDGE', 'DL'] },
  SEA: { id: 'SEA', name: 'Seattle Seahawks', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png', color: '#002244', needs: ['OT', 'LB', 'DL', 'EDGE', 'CB'] },
  IND: { id: 'IND', name: 'Indianapolis Colts', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png', color: '#002c5f', needs: ['CB', 'EDGE', 'DL', 'S', 'TE'] },
  ATL: { id: 'ATL', name: 'Atlanta Falcons', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png', color: '#a71930', needs: ['EDGE', 'CB', 'WR', 'DL', 'LB'] },
  GB: { id: 'GB', name: 'Green Bay Packers', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png', color: '#203731', needs: ['CB', 'S', 'OT', 'IOL', 'DL'] },
  JAX: { id: 'JAX', name: 'Jacksonville Jaguars', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png', color: '#006778', needs: ['OT', 'CB', 'WR', 'DL', 'IOL'] },
};

export const TEAMS: Team[] = Object.values(ALL_TEAMS);

const DRAFT_SEQUENCE = [
  // Round 1
  { id: 'LV', r: 1 }, { id: 'NYJ', r: 1 }, { id: 'ARI', r: 1 }, { id: 'TEN', r: 1 }, { id: 'NYG', r: 1 }, { id: 'CLE', r: 1 }, { id: 'WAS', r: 1 }, { id: 'NO', r: 1 }, { id: 'KC', r: 1 }, { id: 'CIN', r: 1 },
  { id: 'MIA', r: 1 }, { id: 'DAL', r: 1 }, { id: 'LAR', r: 1 }, { id: 'BAL', r: 1 }, { id: 'TB', r: 1 }, { id: 'NYJ', r: 1 }, { id: 'DET', r: 1 }, { id: 'MIN', r: 1 }, { id: 'CAR', r: 1 }, { id: 'DAL', r: 1 },
  { id: 'PIT', r: 1 }, { id: 'LAC', r: 1 }, { id: 'PHI', r: 1 }, { id: 'BUF', r: 1 }, { id: 'CHI', r: 1 }, { id: 'SF', r: 1 }, { id: 'HOU', r: 1 }, { id: 'CLE', r: 1 }, { id: 'LAR', r: 1 }, { id: 'NE', r: 1 },
  { id: 'DEN', r: 1 }, { id: 'SEA', r: 1 },
  // Round 2
  { id: 'NYJ', r: 2 }, { id: 'ARI', r: 2 }, { id: 'TEN', r: 2 }, { id: 'LV', r: 2 }, { id: 'NYG', r: 2 }, { id: 'HOU', r: 2 }, { id: 'CLE', r: 2 }, { id: 'KC', r: 2 }, { id: 'CIN', r: 2 }, { id: 'NO', r: 2 },
  { id: 'MIA', r: 2 }, { id: 'NYJ', r: 2 }, { id: 'BAL', r: 2 }, { id: 'TB', r: 2 }, { id: 'IND', r: 2 }, { id: 'ATL', r: 2 }, { id: 'MIN', r: 2 }, { id: 'DET', r: 2 }, { id: 'CAR', r: 2 }, { id: 'GB', r: 2 },
  { id: 'PIT', r: 2 }, { id: 'PHI', r: 2 }, { id: 'LAC', r: 2 }, { id: 'BUF', r: 2 }, { id: 'CHI', r: 2 }, { id: 'HOU', r: 2 }, { id: 'SF', r: 2 }, { id: 'JAX', r: 2 }, { id: 'LAR', r: 2 }, { id: 'NE', r: 2 },
  { id: 'DEN', r: 2 }, { id: 'SEA', r: 2 },
  // Round 3
  { id: 'ARI', r: 3 }, { id: 'TEN', r: 3 }, { id: 'LV', r: 3 }, { id: 'PHI', r: 3 }, { id: 'HOU', r: 3 }, { id: 'CLE', r: 3 }, { id: 'WAS', r: 3 }, { id: 'CIN', r: 3 }, { id: 'NO', r: 3 }, { id: 'KC', r: 3 },
  { id: 'MIA', r: 3 }, { id: 'PIT', r: 3 }, { id: 'TB', r: 3 }, { id: 'IND', r: 3 }, { id: 'ATL', r: 3 }, { id: 'BAL', r: 3 }, { id: 'JAX', r: 3 }, { id: 'MIN', r: 3 }, { id: 'CAR', r: 3 }, { id: 'GB', r: 3 },
  { id: 'PIT', r: 3 }, { id: 'LAC', r: 3 }, { id: 'MIA', r: 3 }, { id: 'BUF', r: 3 }, { id: 'CHI', r: 3 }, { id: 'SF', r: 3 }, { id: 'MIA', r: 3 }, { id: 'JAX', r: 3 }, { id: 'LAR', r: 3 }, { id: 'NE', r: 3 },
  { id: 'DEN', r: 3 }, { id: 'SEA', r: 3 }, { id: 'MIN', r: 3 }, { id: 'PHI', r: 3 }, { id: 'PIT', r: 3 }, { id: 'JAX', r: 3 }
];

export const INITIAL_DRAFT_ORDER: DraftPick[] = DRAFT_SEQUENCE.map((pick, index) => ({
  pickNumber: index + 1,
  round: pick.r,
  team: ALL_TEAMS[pick.id],
}));

const COLLEGE_IDS: Record<string, number> = {
  'Indiana': 84, 'Oregon': 2483, 'Ohio State': 194, 'Miami (FL)': 2390, 'Arizona State': 9, 'Notre Dame': 87, 'Utah': 254, 'Texas Tech': 2641, 'Auburn': 2, 'Clemson': 228, 'LSU': 99, 'Tennessee': 2633, 'USC': 30, 'Alabama': 333, 'Penn State': 213, 'Washington': 264, 'Texas A&M': 245, 'Georgia': 61, 'Florida': 57, 'South Carolina': 2579, 'Iowa': 2294, 'Louisville': 97, 'Texas': 251, 'Oklahoma': 201, 'Memphis': 235, 'Missouri': 142, 'Toledo': 2649, 'San Diego State': 21, 'Northwestern': 77, 'Arkansas': 8, 'Cincinnati': 2132, 'Boston College': 103, 'Duke': 150, 'Nebraska': 158, 'Illinois': 356, 'SMU': 2567, 'UConn': 41, 'Arizona': 12, 'Iowa State': 66
};

const getEspnUrl = (id: number) => `https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/${id}.png`;
const getCollegeLogoUrl = (college: string) => {
  const id = COLLEGE_IDS[college];
  return id ? `https://a.espncdn.com/i/teamlogos/ncaa/500/${id}.png` : `https://via.placeholder.com/500?text=${encodeURIComponent(college)}`;
};

export const PROSPECTS: Prospect[] = [
  // 1-50 (original set)
  { id: 'p1', name: 'Fernando Mendoza', headshotUrl: getEspnUrl(4837248), college: 'Indiana', position: 'QB', height: '6\'5"', weight: 225, rank: 1, collegeLogoUrl: getCollegeLogoUrl('Indiana'), scoutingReport: 'Prototypical pocket passer with elite ball placement and a massive frame.' },
  { id: 'p2', name: 'Dante Moore', headshotUrl: getEspnUrl(4870921), college: 'Oregon', position: 'QB', height: '6\'3"', weight: 210, rank: 2, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Polished signal-caller with a quick release and natural deep touch.' },
  { id: 'p3', name: 'Arvell Reese', headshotUrl: getEspnUrl(4950400), college: 'Ohio State', position: 'LB', height: '6\'3"', weight: 235, rank: 3, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Modern sideline-to-sideline LB with violent hands and elite speed.' },
  { id: 'p4', name: 'Rueben Bain', headshotUrl: getEspnUrl(4870617), college: 'Miami (FL)', position: 'EDGE', height: '6\'3"', weight: 275, rank: 4, collegeLogoUrl: getCollegeLogoUrl('Miami (FL)'), scoutingReport: 'Relentless motor and elite leverage; sophisticated pass-rush moves.' },
  { id: 'p5', name: 'Carnell Tate', headshotUrl: getEspnUrl(4871023), college: 'Ohio State', position: 'WR', height: '6\'2"', weight: 191, rank: 5, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Refined route runner with exceptional body control.' },
  { id: 'p6', name: 'Jordyn Tyson', headshotUrl: getEspnUrl(4880281), college: 'Arizona State', position: 'WR', height: '6\'1"', weight: 190, rank: 6, collegeLogoUrl: getCollegeLogoUrl('Arizona State'), scoutingReport: 'Dynamic vertical threat with game-breaking speed.' },
  { id: 'p7', name: 'Caleb Downs', headshotUrl: getEspnUrl(4870706), college: 'Ohio State', position: 'S', height: '6\'0"', weight: 205, rank: 7, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Instinctual safety who functions as a coach on the field.' },
  { id: 'p8', name: 'Jeremiyah Love', headshotUrl: getEspnUrl(4870808), college: 'Notre Dame', position: 'RB', height: '6\'0"', weight: 210, rank: 8, collegeLogoUrl: getCollegeLogoUrl('Notre Dame'), scoutingReport: 'Explosive home-run hitter with rare receiving versatility.' },
  { id: 'p9', name: 'Spencer Fano', headshotUrl: getEspnUrl(4870723), college: 'Utah', position: 'OT', height: '6\'5"', weight: 300, rank: 9, collegeLogoUrl: getCollegeLogoUrl('Utah'), scoutingReport: 'Athletic tackle with light feet and great balance.' },
  { id: 'p10', name: 'Francis Mauigoa', headshotUrl: getEspnUrl(4870914), college: 'Miami (FL)', position: 'OT', height: '6\'6"', weight: 342, rank: 10, collegeLogoUrl: getCollegeLogoUrl('Miami (FL)'), scoutingReport: 'Massive road-grader with overwhelming power and nimble feet.' },
  { id: 'p11', name: 'David Bailey', headshotUrl: getEspnUrl(4685248), college: 'Texas Tech', position: 'EDGE', height: '6\'3"', weight: 240, rank: 11, collegeLogoUrl: getCollegeLogoUrl('Texas Tech'), scoutingReport: 'High-energy edge rusher with a quick first step.' },
  { id: 'p12', name: 'Keldric Faulk', headshotUrl: getEspnUrl(4870707), college: 'Auburn', position: 'EDGE', height: '6\'6"', weight: 288, rank: 12, collegeLogoUrl: getCollegeLogoUrl('Auburn'), scoutingReport: 'Rare physical specimen with elite length and levers.' },
  { id: 'p13', name: 'Peter Woods', headshotUrl: getEspnUrl(4871063), college: 'Clemson', position: 'DL', height: '6\'2"', weight: 315, rank: 13, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Violent interior defender with elite hand usage.' },
  { id: 'p14', name: 'Mansoor Delane', headshotUrl: getEspnUrl(4880124), college: 'LSU', position: 'CB', height: '6\'1"', weight: 185, rank: 14, collegeLogoUrl: getCollegeLogoUrl('LSU'), scoutingReport: 'Sticky man-to-man corner with elite mirror-and-match skills.' },
  { id: 'p15', name: 'Jermod McCoy', headshotUrl: getEspnUrl(5157289), college: 'Tennessee', position: 'CB', height: '6\'0"', weight: 193, rank: 15, collegeLogoUrl: getCollegeLogoUrl('Tennessee'), scoutingReport: 'Smooth-moving corner with great recovery speed.' },
  { id: 'p16', name: 'Makai Lemon', headshotUrl: getEspnUrl(4870795), college: 'USC', position: 'WR', height: '5\'11"', weight: 190, rank: 16, collegeLogoUrl: getCollegeLogoUrl('USC'), scoutingReport: 'Twitchy slot specialist with elite short-area quickness.' },
  { id: 'p17', name: 'Sonny Styles', headshotUrl: getEspnUrl(5081807), college: 'Ohio State', position: 'LB', height: '6\'4"', weight: 235, rank: 17, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Versatile hybrid with safety range in an LB body.' },
  { id: 'p18', name: 'Kenyon Sadiq', headshotUrl: getEspnUrl(5083315), college: 'Oregon', position: 'TE', height: '6\'3"', weight: 245, rank: 18, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Modern mismatch nightmare tight end.' },
  { id: 'p19', name: 'Avieon Terrell', headshotUrl: getEspnUrl(4870988), college: 'Clemson', position: 'CB', height: '5\'11"', weight: 180, rank: 19, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Tenacious corner with elite bloodlines.' },
  { id: 'p20', name: 'Ty Simpson', headshotUrl: getEspnUrl(4685522), college: 'Alabama', position: 'QB', height: '6\'2"', weight: 203, rank: 20, collegeLogoUrl: getCollegeLogoUrl('Alabama'), scoutingReport: 'Talented playmaker with a live arm.' },
  { id: 'p21', name: 'Olaivavega Ioane', headshotUrl: getEspnUrl(4832793), college: 'Penn State', position: 'IOL', height: '6\'4"', weight: 350, rank: 21, collegeLogoUrl: getCollegeLogoUrl('Penn State'), scoutingReport: 'Powerful interior blocker with a massive anchor.' },
  { id: 'p22', name: 'Kadyn Proctor', headshotUrl: getEspnUrl(4870976), college: 'Alabama', position: 'OT', height: '6\'7"', weight: 360, rank: 22, collegeLogoUrl: getCollegeLogoUrl('Alabama'), scoutingReport: 'Huge tackle with natural strength and length.' },
  { id: 'p23', name: 'Kayden McDonald', headshotUrl: getEspnUrl(4870893), college: 'Ohio State', position: 'DL', height: '6\'2"', weight: 326, rank: 23, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Classic nose tackle with surprising quickness.' },
  { id: 'p24', name: 'Denzel Boston', headshotUrl: getEspnUrl(4832800), college: 'Washington', position: 'WR', height: '6\'4"', weight: 209, rank: 24, collegeLogoUrl: getCollegeLogoUrl('Washington'), scoutingReport: 'Tall boundary receiver with massive catch radius.' },
  { id: 'p25', name: 'Cashius Howell', headshotUrl: getEspnUrl(4710752), college: 'Texas A&M', position: 'EDGE', height: '6\'4"', weight: 235, rank: 25, collegeLogoUrl: getCollegeLogoUrl('Texas A&M'), scoutingReport: 'Stand-up edge rusher with elite bend and burst.' },
  { id: 'p26', name: 'Caleb Lomu', headshotUrl: getEspnUrl(4921438), college: 'Utah', position: 'OT', height: '6\'5"', weight: 300, rank: 26, collegeLogoUrl: getCollegeLogoUrl('Utah'), scoutingReport: 'High-IQ tackle with great technique.' },
  { id: 'p27', name: 'T.J. Parker', headshotUrl: getEspnUrl(4870886), college: 'Clemson', position: 'EDGE', height: '6\'3"', weight: 255, rank: 27, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Stout edge setter with strong hands.' },
  { id: 'p28', name: 'C.J. Allen', headshotUrl: getEspnUrl(4870598), college: 'Georgia', position: 'LB', height: '6\'1"', weight: 235, rank: 28, collegeLogoUrl: getCollegeLogoUrl('Georgia'), scoutingReport: 'Hard-hitting LB with exceptional gap discipline.' },
  { id: 'p29', name: 'Kevin Concepcion', headshotUrl: getEspnUrl(4870653), college: 'Texas A&M', position: 'WR', height: '5\'11"', weight: 190, rank: 29, collegeLogoUrl: getCollegeLogoUrl('Texas A&M'), scoutingReport: 'Versatile weapon with elite YAC capability.' },
  { id: 'p30', name: 'Caleb Banks', headshotUrl: getEspnUrl(4602019), college: 'Florida', position: 'DL', height: '6\'6"', weight: 325, rank: 30, collegeLogoUrl: getCollegeLogoUrl('Florida'), scoutingReport: 'Unusually tall and long interior presence.' },
  { id: 'p31', name: 'Brandon Cisse', headshotUrl: getEspnUrl(5076652), college: 'South Carolina', position: 'CB', height: '6\'0"', weight: 182, rank: 31, collegeLogoUrl: getCollegeLogoUrl('South Carolina'), scoutingReport: 'Fluid athlete with high-end recovery speed.' },
  { id: 'p32', name: 'Colton Hood', headshotUrl: getEspnUrl(4921249), college: 'Tennessee', position: 'CB', height: '6\'1"', weight: 185, rank: 32, collegeLogoUrl: getCollegeLogoUrl('Tennessee'), scoutingReport: 'Long, athletic corner for press-man coverage.' },
  { id: 'p33', name: 'Matayo Uiagalelei', headshotUrl: getEspnUrl(4871052), college: 'Oregon', position: 'EDGE', height: '6\'5"', weight: 270, rank: 33, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Powerful end with heavy hands.' },
  { id: 'p34', name: 'A\'Mauri Washington', headshotUrl: getEspnUrl(4899488), college: 'Oregon', position: 'DL', height: '6\'3"', weight: 300, rank: 34, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Burst-oriented DT who penetrates the backfield.' },
  { id: 'p35', name: 'Gennings Dunker', headshotUrl: getEspnUrl(4431258), college: 'Iowa', position: 'OT', height: '6\'5"', weight: 320, rank: 35, collegeLogoUrl: getCollegeLogoUrl('Iowa'), scoutingReport: 'Technically sound tackle with high IQ.' },
  { id: 'p36', name: 'Emmanuel Pregnon', headshotUrl: getEspnUrl(4608929), college: 'Oregon', position: 'IOL', height: '6\'5"', weight: 320, rank: 36, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Physical interior blocker with a nasty streak.' },
  { id: 'p37', name: 'Chris Bell', headshotUrl: getEspnUrl(4869961), college: 'Louisville', position: 'WR', height: '6\'2"', weight: 220, rank: 37, collegeLogoUrl: getCollegeLogoUrl('Louisville'), scoutingReport: 'Physical WR who wins through contact.' },
  { id: 'p38', name: 'L.T. Overton', headshotUrl: getEspnUrl(4870960), college: 'Alabama', position: 'EDGE', height: '6\'5"', weight: 265, rank: 38, collegeLogoUrl: getCollegeLogoUrl('Alabama'), scoutingReport: 'Premier physical traits and frame for development.' },
  { id: 'p39', name: 'Anthony Hill Jr.', headshotUrl: getEspnUrl(4870805), college: 'Texas', position: 'LB', height: '6\'3"', weight: 234, rank: 39, collegeLogoUrl: getCollegeLogoUrl('Texas'), scoutingReport: 'Aggressive LB with elite blitzing capability.' },
  { id: 'p40', name: 'Romello Height', headshotUrl: getEspnUrl(4432244), college: 'Texas Tech', position: 'EDGE', height: '6\'3"', weight: 230, rank: 40, collegeLogoUrl: getCollegeLogoUrl('Texas Tech'), scoutingReport: 'Twitchy speed rusher with high-end acceleration.' },
  { id: 'p41', name: 'Christen Miller', headshotUrl: getEspnUrl(4685479), college: 'Georgia', position: 'DL', height: '6\'4"', weight: 305, rank: 41, collegeLogoUrl: getCollegeLogoUrl('Georgia'), scoutingReport: 'Powerful presence with elite leverage.' },
  { id: 'p42', name: 'R Mason Thomas', headshotUrl: getEspnUrl(5081927), college: 'Oklahoma', position: 'EDGE', height: '6\'2"', weight: 245, rank: 42, collegeLogoUrl: getCollegeLogoUrl('Oklahoma'), scoutingReport: 'High-motor defender with great counters.' },
  { id: 'p43', name: 'Chris Adams', headshotUrl: getEspnUrl(4698083), college: 'Memphis', position: 'IOL', height: '6\'3"', weight: 290, rank: 43, collegeLogoUrl: getCollegeLogoUrl('Memphis'), scoutingReport: 'Athletic pulling guard with great quickness.' },
  { id: 'p44', name: 'Dillon Thieneman', headshotUrl: getEspnUrl(4954445), college: 'Oregon', position: 'S', height: '6\'0"', weight: 205, rank: 44, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Center-field safety with elite range.' },
  { id: 'p45', name: 'Garrett Nussmeier', headshotUrl: getEspnUrl(4567747), college: 'LSU', position: 'QB', height: '6\'2"', weight: 205, rank: 45, collegeLogoUrl: getCollegeLogoUrl('LSU'), scoutingReport: 'Confident gunslinger with a quick release.' },
  { id: 'p46', name: 'Zion Young', headshotUrl: getEspnUrl(4839501), college: 'Missouri', position: 'EDGE', height: '6\'6"', weight: 265, rank: 46, collegeLogoUrl: getCollegeLogoUrl('Missouri'), scoutingReport: 'Long, developmental edge with massive upside.' },
  { id: 'p47', name: 'Chris Brazzell', headshotUrl: getEspnUrl(5091739), college: 'Tennessee', position: 'WR', height: '6\'5"', weight: 200, rank: 47, collegeLogoUrl: getCollegeLogoUrl('Tennessee'), scoutingReport: 'Lanky vertical threat with elite leaping ability.' },
  { id: 'p48', name: 'Emmanuel McNeil-Warren', headshotUrl: getEspnUrl(4837186), college: 'Toledo', position: 'S', height: '6\'2"', weight: 200, rank: 48, collegeLogoUrl: getCollegeLogoUrl('Toledo'), scoutingReport: 'Physical box safety who sheds blocks well.' },
  { id: 'p49', name: 'Keith Abney II', headshotUrl: getEspnUrl(5093004), college: 'Arizona State', position: 'CB', height: '5\'10"', weight: 185, rank: 49, collegeLogoUrl: getCollegeLogoUrl('Arizona State'), scoutingReport: 'Scrappy corner with elite short-area quickness.' },
  { id: 'p50', name: 'Chris Johnson', headshotUrl: getEspnUrl(4869579), college: 'San Diego State', position: 'CB', height: '6\'0"', weight: 180, rank: 50, collegeLogoUrl: getCollegeLogoUrl('San Diego State'), scoutingReport: 'Technically sound with smooth mechanics.' },
  // 51-100 (newly requested set)
  { id: 'p51', name: 'Lee Hunter', headshotUrl: getEspnUrl(4568282), college: 'Texas Tech', position: 'DL', height: '6\'4"', weight: 320, rank: 51, collegeLogoUrl: getCollegeLogoUrl('Texas Tech'), scoutingReport: 'Powerful run-stuffer with interior push.' },
  { id: 'p52', name: 'Elijah Sarratt', headshotUrl: getEspnUrl(4920251), college: 'Indiana', position: 'WR', height: '6\'2"', weight: 205, rank: 52, collegeLogoUrl: getCollegeLogoUrl('Indiana'), scoutingReport: 'Fluid route runner with strong catch efficiency.' },
  { id: 'p53', name: 'Caleb Tiernan', headshotUrl: getEspnUrl(4685050), college: 'Northwestern', position: 'OT', height: '6\'7"', weight: 315, rank: 53, collegeLogoUrl: getCollegeLogoUrl('Northwestern'), scoutingReport: 'Massive frame and consistent pass protection technique.' },
  { id: 'p54', name: 'Zachariah Branch', headshotUrl: getEspnUrl(4870632), college: 'Georgia', position: 'WR', height: '5\'10"', weight: 175, rank: 54, collegeLogoUrl: getCollegeLogoUrl('Georgia'), scoutingReport: 'Electric returner and deep threat with rare agility.' },
  { id: 'p55', name: 'Blake Miller', headshotUrl: getEspnUrl(4869814), college: 'Clemson', position: 'OT', height: '6\'6"', weight: 310, rank: 55, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Sturdy right tackle with high-level starting experience.' },
  { id: 'p56', name: 'Akheem Mesidor', headshotUrl: getEspnUrl(4430162), college: 'Miami (FL)', position: 'EDGE', height: '6\'3"', weight: 280, rank: 56, collegeLogoUrl: getCollegeLogoUrl('Miami (FL)'), scoutingReport: 'Versatile defensive lineman with strong interior rush.' },
  { id: 'p57', name: 'Mike Washington Jr.', headshotUrl: getEspnUrl(4880521), college: 'Arkansas', position: 'RB', height: '5\'11"', weight: 215, rank: 57, collegeLogoUrl: getCollegeLogoUrl('Arkansas'), scoutingReport: 'Hard-nosed runner who excels between the tackles.' },
  { id: 'p58', name: 'Austin Siereveld', headshotUrl: getEspnUrl(4950403), college: 'Ohio State', position: 'OT', height: '6\'5"', weight: 320, rank: 58, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Developmental tackle with high functional strength.' },
  { id: 'p59', name: 'Germie Bernard', headshotUrl: getEspnUrl(4880221), college: 'Alabama', position: 'WR', height: '6\'1"', weight: 203, rank: 59, collegeLogoUrl: getCollegeLogoUrl('Alabama'), scoutingReport: 'Consistent chain-mover with reliable hands.' },
  { id: 'p60', name: 'Malik Muhammad', headshotUrl: getEspnUrl(4870817), college: 'Texas', position: 'CB', height: '6\'0"', weight: 185, rank: 60, collegeLogoUrl: getCollegeLogoUrl('Texas'), scoutingReport: 'Sticky cover corner with great transition quickness.' },
  { id: 'p61', name: 'A.J. Haulcy', headshotUrl: getEspnUrl(4920401), college: 'LSU', position: 'S', height: '6\'0"', weight: 210, rank: 61, collegeLogoUrl: getCollegeLogoUrl('LSU'), scoutingReport: 'Ball-hawking safety with great closing burst.' },
  { id: 'p62', name: 'Jake Golday', headshotUrl: getEspnUrl(5121248), college: 'Cincinnati', position: 'LB', height: '6\'4"', weight: 235, rank: 62, collegeLogoUrl: getCollegeLogoUrl('Cincinnati'), scoutingReport: 'Rangy linebacker with high football IQ.' },
  { id: 'p63', name: 'Joshua Josephs', headshotUrl: getEspnUrl(4870762), college: 'Tennessee', position: 'EDGE', height: '6\'3"', weight: 242, rank: 63, collegeLogoUrl: getCollegeLogoUrl('Tennessee'), scoutingReport: 'Twitchy edge rusher who wins with speed-to-power.' },
  { id: 'p64', name: 'Kamari Ramsey', headshotUrl: getEspnUrl(4870982), college: 'USC', position: 'S', height: '6\'1"', weight: 204, rank: 64, collegeLogoUrl: getCollegeLogoUrl('USC'), scoutingReport: 'Instinctual safety who thrives in zone coverage.' },
  { id: 'p65', name: 'Monroe Freeling', headshotUrl: getEspnUrl(4870732), college: 'Georgia', position: 'OT', height: '6\'7"', weight: 310, rank: 65, collegeLogoUrl: getCollegeLogoUrl('Georgia'), scoutingReport: 'High-upside tackle with elite reach and length.' },
  { id: 'p66', name: 'Jadarian Price', headshotUrl: getEspnUrl(4870962), college: 'Notre Dame', position: 'RB', height: '5\'10"', weight: 203, rank: 66, collegeLogoUrl: getCollegeLogoUrl('Notre Dame'), scoutingReport: 'Slashing back with home-run speed.' },
  { id: 'p67', name: 'Zakee Wheatley', headshotUrl: getEspnUrl(4685241), college: 'Penn State', position: 'S', height: '6\'2"', weight: 198, rank: 67, collegeLogoUrl: getCollegeLogoUrl('Penn State'), scoutingReport: 'Versatile secondary player with great range.' },
  { id: 'p68', name: 'Isaiah World', headshotUrl: getEspnUrl(4921401), college: 'Oregon', position: 'OT', height: '6\'5"', weight: 305, rank: 68, collegeLogoUrl: getCollegeLogoUrl('Oregon'), scoutingReport: 'Athletic blocker with high upside in zone schemes.' },
  { id: 'p69', name: 'Max Iheanachor', headshotUrl: getEspnUrl(5151248), college: 'Arizona State', position: 'OT', height: '6\'6"', weight: 315, rank: 69, collegeLogoUrl: getCollegeLogoUrl('Arizona State'), scoutingReport: 'Powerful road-grader with interior flexibility.' },
  { id: 'p70', name: 'Carter Smith', headshotUrl: getEspnUrl(4920258), college: 'Indiana', position: 'OT', height: '6\'5"', weight: 300, rank: 70, collegeLogoUrl: getCollegeLogoUrl('Indiana'), scoutingReport: 'Technically sound with reliable footwork.' },
  { id: 'p71', name: 'Chase Bisontis', headshotUrl: getEspnUrl(4870624), college: 'Texas A&M', position: 'IOL', height: '6\'6"', weight: 320, rank: 71, collegeLogoUrl: getCollegeLogoUrl('Texas A&M'), scoutingReport: 'Versatile lineman who can play guard or tackle.' },
  { id: 'p72', name: 'Jonah Coleman', headshotUrl: getEspnUrl(4832801), college: 'Washington', position: 'RB', height: '5\'9"', weight: 225, rank: 72, collegeLogoUrl: getCollegeLogoUrl('Washington'), scoutingReport: 'Bowling ball runner with elite contact balance.' },
  { id: 'p73', name: 'Ja\'Kobi Lane', headshotUrl: getEspnUrl(4870782), college: 'USC', position: 'WR', height: '6\'4"', weight: 195, rank: 73, collegeLogoUrl: getCollegeLogoUrl('USC'), scoutingReport: 'Height specialist with elite contested catch skills.' },
  { id: 'p74', name: 'D\'angelo Ponds', headshotUrl: getEspnUrl(5121251), college: 'Indiana', position: 'CB', height: '5\'9"', weight: 175, rank: 74, collegeLogoUrl: getCollegeLogoUrl('Indiana'), scoutingReport: 'Pint-sized corner with elite mirror-and-match.' },
  { id: 'p75', name: 'Connor Lew', headshotUrl: getEspnUrl(4870798), college: 'Auburn', position: 'IOL', height: '6\'3"', weight: 302, rank: 75, collegeLogoUrl: getCollegeLogoUrl('Auburn'), scoutingReport: 'High-IQ center with elite leverage in the run game.' },
  { id: 'p76', name: 'Domonique Orange', headshotUrl: getEspnUrl(4839521), college: 'Iowa State', position: 'DL', height: '6\'4"', weight: 335, rank: 76, collegeLogoUrl: getCollegeLogoUrl('Iowa State'), scoutingReport: 'Massive interior force who commands double teams.' },
  { id: 'p77', name: 'Caden Curry', headshotUrl: getEspnUrl(4685458), college: 'Ohio State', position: 'EDGE', height: '6\'3"', weight: 250, rank: 77, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'High-motor defender with great pursuit speed.' },
  { id: 'p78', name: 'KP Price', headshotUrl: getEspnUrl(5081248), college: 'Boston College', position: 'S', height: '6\'1"', weight: 195, rank: 78, collegeLogoUrl: getCollegeLogoUrl('Boston College'), scoutingReport: 'Physical safety with high-end tackling efficiency.' },
  { id: 'p79', name: 'Dani Dennis-Sutton', headshotUrl: getEspnUrl(4870672), college: 'Penn State', position: 'EDGE', height: '6\'5"', weight: 270, rank: 79, collegeLogoUrl: getCollegeLogoUrl('Penn State'), scoutingReport: 'Powerful edge setter with interior versatility.' },
  { id: 'p80', name: 'Julian Neal', headshotUrl: getEspnUrl(4880528), college: 'Arkansas', position: 'CB', height: '6\'2"', weight: 190, rank: 80, collegeLogoUrl: getCollegeLogoUrl('Arkansas'), scoutingReport: 'Tall boundary corner with long-speed reach.' },
  { id: 'p81', name: 'Malachi Fields', headshotUrl: getEspnUrl(4567248), college: 'Notre Dame', position: 'WR', height: '6\'4"', weight: 220, rank: 81, collegeLogoUrl: getCollegeLogoUrl('Notre Dame'), scoutingReport: 'Big-bodied receiver with elite catch-radius.' },
  { id: 'p82', name: 'Cade Klubnik', headshotUrl: getEspnUrl(4685514), college: 'Clemson', position: 'QB', height: '6\'2"', weight: 205, rank: 82, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Athletic playmaker with high-end arm talent.' },
  { id: 'p83', name: 'Kenyatta Jackson', headshotUrl: getEspnUrl(4685459), college: 'Ohio State', position: 'EDGE', height: '6\'5"', weight: 258, rank: 83, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Long-levered rusher with great initial burst.' },
  { id: 'p84', name: 'Deontae Lawson', headshotUrl: getEspnUrl(4431521), college: 'Alabama', position: 'LB', height: '6\'2"', weight: 230, rank: 84, collegeLogoUrl: getCollegeLogoUrl('Alabama'), scoutingReport: 'Physical signal-caller for the defense.' },
  { id: 'p85', name: 'Chandler Rivers', headshotUrl: getEspnUrl(4831248), college: 'Duke', position: 'CB', height: '5\'10"', weight: 178, rank: 85, collegeLogoUrl: getCollegeLogoUrl('Duke'), scoutingReport: 'Technically sound nickel specialist.' },
  { id: 'p86', name: 'Dontay Corleone', headshotUrl: getEspnUrl(4831249), college: 'Cincinnati', position: 'DL', height: '6\'1"', weight: 320, rank: 86, collegeLogoUrl: getCollegeLogoUrl('Cincinnati'), scoutingReport: 'Elite run stuffer with surprising interior push.' },
  { id: 'p87', name: 'Jake Slaughter', headshotUrl: getEspnUrl(4831250), college: 'Florida', position: 'IOL', height: '6\'5"', weight: 310, rank: 87, collegeLogoUrl: getCollegeLogoUrl('Florida'), scoutingReport: 'Reliable interior blocker with high functional IQ.' },
  { id: 'p88', name: 'Emmett Johnson', headshotUrl: getEspnUrl(4831251), college: 'Nebraska', position: 'RB', height: '5\'11"', weight: 200, rank: 88, collegeLogoUrl: getCollegeLogoUrl('Nebraska'), scoutingReport: 'Explosive back with great home-run potential.' },
  { id: 'p89', name: 'Will Lee III', headshotUrl: getEspnUrl(4831252), college: 'Texas A&M', position: 'CB', height: '6\'3"', weight: 185, rank: 89, collegeLogoUrl: getCollegeLogoUrl('Texas A&M'), scoutingReport: 'Tall corner with natural tracking skills.' },
  { id: 'p90', name: 'Taurean York', headshotUrl: getEspnUrl(4831253), college: 'Texas A&M', position: 'LB', height: '6\'0"', weight: 230, rank: 90, collegeLogoUrl: getCollegeLogoUrl('Texas A&M'), scoutingReport: 'Highly instinctual LB with elite tackling range.' },
  { id: 'p91', name: 'Max Klare', headshotUrl: getEspnUrl(4831254), college: 'Ohio State', position: 'TE', height: '6\'4"', weight: 245, rank: 91, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Consistent chain-mover at tight end.' },
  { id: 'p92', name: 'Gabe Jacas', headshotUrl: getEspnUrl(4831255), college: 'Illinois', position: 'EDGE', height: '6\'3"', weight: 265, rank: 92, collegeLogoUrl: getCollegeLogoUrl('Illinois'), scoutingReport: 'Powerful edge defender with interior rush ability.' },
  { id: 'p93', name: 'Omar Cooper Jr.', headshotUrl: getEspnUrl(4831256), college: 'Indiana', position: 'WR', height: '6\'1"', weight: 200, rank: 93, collegeLogoUrl: getCollegeLogoUrl('Indiana'), scoutingReport: 'Deep threat specialist with great tracking skills.' },
  { id: 'p94', name: 'Logan Parr', headshotUrl: getEspnUrl(4831257), college: 'SMU', position: 'IOL', height: '6\'4"', weight: 315, rank: 94, collegeLogoUrl: getCollegeLogoUrl('SMU'), scoutingReport: 'Dependable interior lineman with great strength.' },
  { id: 'p95', name: 'Skyler Bell', headshotUrl: getEspnUrl(4831258), college: 'UConn', position: 'WR', height: '6\'0"', weight: 190, rank: 95, collegeLogoUrl: getCollegeLogoUrl('UConn'), scoutingReport: 'Speedy receiver with high separation ability.' },
  { id: 'p96', name: 'Davison Igbinosun', headshotUrl: getEspnUrl(4831259), college: 'Ohio State', position: 'CB', height: '6\'2"', weight: 190, rank: 96, collegeLogoUrl: getCollegeLogoUrl('Ohio State'), scoutingReport: 'Long-armed corner for press-man coverage.' },
  { id: 'p97', name: 'Antonio Williams', headshotUrl: getEspnUrl(4831260), college: 'Clemson', position: 'WR', height: '5\'11"', weight: 190, rank: 97, collegeLogoUrl: getCollegeLogoUrl('Clemson'), scoutingReport: 'Refined slot weapon with elite route technique.' },
  { id: 'p98', name: 'Joe Royer', headshotUrl: getEspnUrl(4831261), college: 'Cincinnati', position: 'TE', height: '6\'5"', weight: 255, rank: 98, collegeLogoUrl: getCollegeLogoUrl('Cincinnati'), scoutingReport: 'Prototypical TE frame with reliable hands.' },
  { id: 'p99', name: 'Genesis Smith', headshotUrl: getEspnUrl(4831262), college: 'Arizona', position: 'S', height: '6\'2"', weight: 200, rank: 99, collegeLogoUrl: getCollegeLogoUrl('Arizona'), scoutingReport: 'Versatile secondary player with high range.' },
  { id: 'p100', name: 'Keionte Scott', headshotUrl: getEspnUrl(4831263), college: 'Miami (FL)', position: 'CB', height: '6\'0"', weight: 188, rank: 100, collegeLogoUrl: getCollegeLogoUrl('Miami (FL)'), scoutingReport: 'Physical corner with high defensive awareness.' },
];
